# Generated by Django 3.2.3 on 2021-05-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.choicequestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multichoicesanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.multichoicesquestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.textquestion'),
            preserve_default=False,
        ),
    ]
