# Generated by Django 3.2.3 on 2021-05-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210518_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswerowner',
            old_name='owner',
            new_name='user',
        ),
    ]
